### ISSUE TITLE
Error while fetching tables

### ISSUE THREAD

**Issue by matteocollina** [emabee/rust-hdbconnect#26]
I have a problem retrieving tables via this query: `select SCHEMA_NAME||'|TABLE_NAME from tables`. The tables in question are more than 2000, do you know if there is any timeout or limitation of the plugin?

Thanks

**Comment by emabee** [comment]
I’m not aware of any such limit - there are limits on DB side, but I don’t think you hit them. 
What error did you get?
Is this valid SQL? Shouldn‘t it be
`select SCHEMA_NAME, TABLE_NAME from tables`?
