### ISSUE TITLE
Feature Request: Set packet size

### ISSUE THREAD

**Issue by kand617** [emabee/rust-hdbconnect#28]
Some SAP clients allow you to set the packet size for better performance. Is this possible in rust version?

**Comment by emabee** [comment]
Not sure what exactly setting the packet size does...

`hdbconnect` has these:
- [`Connection::set_fetch_size`](https://docs.rs/hdbconnect/latest/hdbconnect/struct.Connection.html#method.set_fetch_size)
- [`Connection::set_lob_read_length`](https://docs.rs/hdbconnect/latest/hdbconnect/struct.Connection.html#method.set_lob_read_length) 
- [`Connection::set_lob_write_length`](https://docs.rs/hdbconnect/latest/hdbconnect/struct.Connection.html#method.set_lob_write_length)

which can indeed have significant impact on performance.

Is this what you need? Are you missing something?

**Comment by kand617** [comment]
HI @emabee 

I need to be setting other client opts as shown here:

```
hdbconnect_impl/src/protocol/parts/connect_options.rs

    CompressionLevelAndFlags,          // 49 // Network compression level and flags (hana2sp02)
```

**Comment by emabee** [comment]
Not yet implemented – I‘ll give it a try.

**Comment by emabee** [comment]
Compression is now realised and used by default!
0.28.3 also comes with an easy way to provide non-default values for some configurable parameters (see [Connection::with_configuration](https://docs.rs/hdbconnect_async/latest/hdbconnect_async/struct.Connection.html#method.with_configuration)).

**Comment by kand617** [comment]
Wow thats awesome! Compression is seamless to the caller of SDK right. 
No logic changes for existing callers?

**Comment by emabee** [comment]
Correct :-)
