### ISSUE TITLE
Rustls fails with UnsupportedCertVersion despite tls_without_server_verification

### ISSUE THREAD

**Issue by philwinn** [emabee/rust-hdbconnect#29]
Using
```rust
let hdb_conn_params = ConnectParams::builder()
    .tls_without_server_verification()
    [...]
let hdb_conn = hdbconnect::Connection::new(hdb_conn_params).expect("Failed to connect to HANA database");
```
fails with
```
DEBUG hdbconnect_impl::conn::tcp_client::sync_tls_tcp_client: Connecting to "..."    
DEBUG rustls::client::hs: No cached session for IpAddress(...)    
DEBUG rustls::client::hs: Not resuming any session    
DEBUG rustls::client::hs: ALPN protocol is None    
DEBUG rustls::client::hs: Using ciphersuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256    
DEBUG rustls::client::tls12: ECDHE curve is ECParameters { curve_type: NamedCurve, named_group: secp384r1 }    
DEBUG rustls::client::tls12: Server DNS name is IpAddress(...)    
WARN rustls::conn: Sending fatal alert BadCertificate    
thread 'main' panicked at 'Failed to connect to HANA database: Io { source: Custom { kind: Other, error: InvalidCertificateData("invalid peer certificate: UnsupportedCertVersion") } }'
```
My guess: Seems that `rustls` is verifying correctness of any cert before the actual validation process is conducted?

Also tried the `"dangerous_configuration"` feature for rustls, but that doesn't change anything.  
Any idea what might be incorrectly configured here?

Thank you for implementing this library and I very much appreciate any help!

**Comment by emabee** [comment]
I assume that this call fails:
```rust
let config = rustls::client::ClientConfig::builder()
    .with_safe_defaults()
    .with_custom_certificate_verifier(Arc::new(NoCertificateVerification {}))
    .with_no_client_auth();
 ```


This is what the docu says about `with_safe_defaults()`:

> Start side-specific config with defaults for underlying cryptography.
> 
> If used, this will enable all safe supported cipher suites ([DEFAULT_CIPHER_SUITES](https://docs.rs/rustls/latest/rustls/static.DEFAULT_CIPHER_SUITES.html)), all safe supported key exchange groups ([ALL_KX_GROUPS](https://docs.rs/rustls/latest/rustls/static.ALL_KX_GROUPS.html)) and all safe supported protocol versions ([DEFAULT_VERSIONS](https://docs.rs/rustls/latest/rustls/static.DEFAULT_VERSIONS.html)).
> 
> These are safe defaults, useful for 99% of applications.
> 

I would not want to remove that, but maybe this gives a hint to what is wrong with your certificate.
