### ISSUE TITLE
Query Execution Stuck while fetching new rows

### ISSUE THREAD

**Issue by kand617** [emabee/rust-hdbconnect#30]
There appears to be an intermittent issue where the code simply waits forever while fetching the rows.
I suspect the connection got dropped somewhere.

Is it possible to add some timeout for when getting the next set of rows?

```
 let rs = connection.query(query).await;
 while let Some(row) = rs.next_row().await.unwrap() {

}
```

**Comment by kand617** [comment]
Sorry I could not reproduce this. The production code worked right after I terminated and restarted. 

I am using:
1 async method
1 connection, 
size of the result is 7 columns *1000 rows
tokio runtime. 

I don't think its a SDK issue but rather a server issue. 
However, I think its good to have some timeouts. 
Is it possible to do wrap rs.next_rows() with some outer timeout function?

**Comment by emabee** [comment]
OK, point taken. A client-side timeout would make sense in both `hdbconnect` and `hdbconnect_async`.

**Comment by emabee** [comment]
0.28.4 now allows specifying a read timeout 😀
